DROP TABLE IF EXISTS haiku;

CREATE TABLE haiku (
  id SERIAL PRIMARY KEY NOT NULL,
  author VARCHAR(255) NOT NULL,
  content TEXT NOT NULL
  
);

INSERT INTO haiku (author, content) 
VALUES ('松尾 芭蕉 (Matsuo Bashō)', E'Scarecrow in the hillock\nPaddy field --\nHow unaware!  How useful!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Passing through the world\nIndeed this is just\nSogi''s rain shelter.'),
('松尾 芭蕉 (Matsuo Bashō)', E'A wild sea-\nIn the distance over Sado\nThe Milky Way.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The she cat -\nGrown thin\nFrom love and barley.'),
('松尾 芭蕉 (Matsuo Bashō)', E'How wild the sea is,\nand over Sado Island,\nthe River of Heaven'),
('松尾 芭蕉 (Matsuo Bashō)', E'Morning and evening\nSomeone waits at Matsushima!\nOne-sided love.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Wrapping dumplings in \nbamboo leaves, with one finger\nshe tidies her hair'),
('松尾 芭蕉 (Matsuo Bashō)', E'On Buddha''s birthday\na spotted fawn is born –\njust like that'),
('松尾 芭蕉 (Matsuo Bashō)', E'On Buddha''s deathday,\nwrinkled tough old hands pray –\nthe prayer beads'' sound'),
('松尾 芭蕉 (Matsuo Bashō)', E'I like to wash,\nthe dust of this world\nIn the droplets of dew.'),
('松尾 芭蕉 (Matsuo Bashō)', E'With dewdrops dripping,\nI wish somehow I could wash \nthis perishing world'),
('松尾 芭蕉 (Matsuo Bashō)', E'Won''t you come and see\nloneliness? Just one leaf\nfrom the kiri tree.'),
('松尾 芭蕉 (Matsuo Bashō)', E'moonless night...\na powerful wind embraces\nthe ancient cedars'),
('松尾 芭蕉 (Matsuo Bashō)', E'Behind Ise Shrine,\nunseen, hidden by the fence,\nBuddha enters nirvana'),
('松尾 芭蕉 (Matsuo Bashō)', E'This ruined temple\nshould have its sad tale told only\nby a clam digger '),
('松尾 芭蕉 (Matsuo Bashō)', E'in my new clothing\ni feel so different, i must\nlook like someone else'),
('松尾 芭蕉 (Matsuo Bashō)', E'low tide morning...\nthe willow skirts are tailed\nin stinking mud'),
('松尾 芭蕉 (Matsuo Bashō)', E'A green willow,\ndripping down into the mud,\nat low tide.'),
('松尾 芭蕉 (Matsuo Bashō)', E'a clear waterfall —\ninto the ripples\nfall green pine-needles'),
('松尾 芭蕉 (Matsuo Bashō)', E'overhanging pine...\nadding its mite of needles\nto the waterfall'),
('松尾 芭蕉 (Matsuo Bashō)', E'The pine tree of Shiogoshi\nTrickles all night long\nShiny drops of moonlight.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Culture''s beginnings:\nrice-planting songs from the heart\nof the country'),
('松尾 芭蕉 (Matsuo Bashō)', E'Singing, planting rice,\nvillage songs more lovely\nthan famous city poems'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring air --\nWoven moon\nAnd plum scent.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Heated spring air\nIn tiny waves of an inch or two -\nAbove wintery grass.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Fresh spring!\nThe world is only Nine days old -\nThese fields and mountains!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring!\nA nameless hill\nin the haze.'),
('松尾 芭蕉 (Matsuo Bashō)', E'it is spring!\na hill without a name\nin thin haze'),
('松尾 芭蕉 (Matsuo Bashō)', E'Oh, these spring days!\nA nameless little mountain,\nwrapped in morning haze!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring too, very soon!\nThey are setting the scene for it --\nplum tree and moon.'),
('松尾 芭蕉 (Matsuo Bashō)', E'From all directions\nWinds bring petals of cherry\nInto the grebe lake.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The leafless cherry,\nOld as a toothless woman,\nBlooms in flowers,\nMindful of its youth.'),
('松尾 芭蕉 (Matsuo Bashō)', E'That great blue oak\nindifferent to all blossoms\nappears more noble'),
('松尾 芭蕉 (Matsuo Bashō)', E'The oak tree stands\nnoble on the hill even in\ncherry blossom time'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring rain\nconveyed under the trees\nin drops.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring rain\nLeaking through the roof,\nDripping from the wasps'' nest.'),
('松尾 芭蕉 (Matsuo Bashō)', E'In this warm spring rain,\ntiny leaves are sprouting\nfrom the eggplant seed'),
('松尾 芭蕉 (Matsuo Bashō)', E'The sun''s way:\nhollyhocks turn toward it\nthrough all the rains of May.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring departs.\nBirds cry\nFishes'' eyes are filled with tears'),
('松尾 芭蕉 (Matsuo Bashō)', E'No blossoms and no moon,\nand he is drinking sake\nall alone!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Temple bells die out.\nThe fragrant blossoms remain.\nA perfect evening!'),
('松尾 芭蕉 (Matsuo Bashō)', E'A little girl under a peach tree,\nWhose blossoms fall into the entrails\nOf the earth.'),
('松尾 芭蕉 (Matsuo Bashō)', E'By the old temple,\npeach blossoms;\na man treading rice.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Unknown spring --\nPlum blossom\nBehind the mirror.'),
('松尾 芭蕉 (Matsuo Bashō)', E'With plum blossom scent,\nthis sudden sun emerges\nalong a mountain trail'),
('松尾 芭蕉 (Matsuo Bashō)', E'Very brief:\nGleam of blossoms in the treetops\nOn a moonlit night.'),
('松尾 芭蕉 (Matsuo Bashō)', E'A lovely spring night\nsuddenly vanished while we\nviewed cherry blossoms.'),
('松尾 芭蕉 (Matsuo Bashō)', E'From every direction\ncherry blossom petals blow\ninto Lake Biwa'),
('松尾 芭蕉 (Matsuo Bashō)', E'Kannon''s* tiled temple\nroof floats far away in clouds\nof cherry blossoms\n(Bodhisattva of Compassion)'),
('松尾 芭蕉 (Matsuo Bashō)', E'From all these trees –\nin salads, soups, everywhere –\ncherry blossoms fall'),
('松尾 芭蕉 (Matsuo Bashō)', E'Cedar umbrellas, off\nto Mount Yoshimo for\nthe cherry blossoms.'),
('松尾 芭蕉 (Matsuo Bashō)', E'On a journey,\nResting beneath the cherry blossoms,\nI feel myself to be in a Noh play.'),
('松尾 芭蕉 (Matsuo Bashō)', E'in the blossoms’ shade\nas in the noh drama\na traveller sleeps'),
('松尾 芭蕉 (Matsuo Bashō)', E'Clouds of cherry blossoms!\nIs that temple bell in Ueno\nor Asakusa?'),
('松尾 芭蕉 (Matsuo Bashō)', E'The temple bell stops.\nBut the sound keeps coming\nout of the flowers.'),
('松尾 芭蕉 (Matsuo Bashō)', E'all the more I wish to see\nin those blossoms at dawn\nthe face of a god'),
('松尾 芭蕉 (Matsuo Bashō)', E'Searching storehouse eaves,\nrapt in plum blossom smells,\nthe mosquito hums'),
('松尾 芭蕉 (Matsuo Bashō)', E'Bush clover in blossom waves\nWithout spilling\nA drop of dew.'),
('松尾 芭蕉 (Matsuo Bashō)', E'the moon still is\nthough it seems far from home\nSuma in summer'),
('松尾 芭蕉 (Matsuo Bashō)', E'Taking a nap,\nFeet planted\nAgainst a cool wall.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Melon\nIn morning dew,\nmud-fresh.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Wet with morning dew\nand splotched with mud, the melon\nlooks especially cool'),
('松尾 芭蕉 (Matsuo Bashō)', E'The old pond:\na frog jumps in,-\nthe sound of water.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Frog pond --\nA leaf falls in\nWithout a sound'),
('松尾 芭蕉 (Matsuo Bashō)', E'The old pond;\nthe frog.\nPlop!'),
('松尾 芭蕉 (Matsuo Bashō)', E'At the ancient pond\na frog plunges into\nthe sound of water'),
('松尾 芭蕉 (Matsuo Bashō)', E'Summer moon -\nClapping hands,\nI herald dawn.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Mogami River, yanking\nThe burning sky\nInto the sea.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Yellow rose petals\nThunder -\nA waterfall.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Cold white azalea -\nLone nun\nUnder thatched roof.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Three months after we saw\nCherry blossoms together\nI came to see the glorious\nTwin trunks of the pine.'),
('松尾 芭蕉 (Matsuo Bashō)', E'I felt quite at home,\nAs if it were mine sleeping lazily\nIn this house of fresh air.'),
('松尾 芭蕉 (Matsuo Bashō)', E'June clouds,\nAt ease on\nArashiyama Peak.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Octopus traps -\nsummer’s moonspun dreams,\nsoon ended.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Summer in the world;\nfloating on the waves\nof the lake.'),
('松尾 芭蕉 (Matsuo Bashō)', E'in your summer-room...\ngarden and mountain going too\nas we slowly walk'),
('松尾 芭蕉 (Matsuo Bashō)', E'Even leaves don''t move\nAwesome is the\nSummer grove'),
('松尾 芭蕉 (Matsuo Bashō)', E'The summer''s grass!\nall that''s left\nof ancient warriors'' dreams.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Summer grasses:\nall that remains of great soldiers’\nimperial dreams'),
('松尾 芭蕉 (Matsuo Bashō)', E'A thicket of summer grass\nIs all that remains\nOf the dreams of ancient warriors.'),
('松尾 芭蕉 (Matsuo Bashō)', E'All the rains of June\nit brings together, and it is swift --\nthe river Morgami.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Summer zashiki\nMake move and enter\nThe mountain and the garden.'),
('松尾 芭蕉 (Matsuo Bashō)', E'This hot day swept away\ninto the sea by the\nMogami River'),
('松尾 芭蕉 (Matsuo Bashō)', E'A lightning gleam:\ninto darkness travels\na night heron''s scream.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Along the roadside,\nblossoming wild roses\nin my horse’s mouth'),
('松尾 芭蕉 (Matsuo Bashō)', E'The farmer''s roadside\nhedge provided lunch for\nmy tired horse'),
('松尾 芭蕉 (Matsuo Bashō)', E'My horse\nClip-clopping over the fields--Oh ho!\nI too am part of the picture!'),
('松尾 芭蕉 (Matsuo Bashō)', E'All day in grey rain\nhollyhocks follow the sun''s\ninvisible road'),
('松尾 芭蕉 (Matsuo Bashō)', E'An ivy spray\nTrained up over the wall\nAnd a few bamboos\nInviting a tempest.'),
('松尾 芭蕉 (Matsuo Bashō)', E'How many priests\nHow many morning glories\nHave perished under the pine\nEternal as law?'),
('松尾 芭蕉 (Matsuo Bashō)', E'along the mountain road\nsomehow it tugs at my heart—\na wild violet'),
('松尾 芭蕉 (Matsuo Bashō)', E'Traveling this high\nmountain trail, delighted\nby violets'),
('松尾 芭蕉 (Matsuo Bashō)', E'looking carefully,\na shepherds purse is blooming\nunder the fence'),
('松尾 芭蕉 (Matsuo Bashō)', E'petal by petal\nyellow mountain roses fall—\nsound of rapids'),
('松尾 芭蕉 (Matsuo Bashō)', E'Petals of the mountain rose\nFall now and then,\nTo the sound of the waterfall?'),
('松尾 芭蕉 (Matsuo Bashō)', E'The petals tremble\non the yellow mountain rose –\nroar of the rapids'),
('松尾 芭蕉 (Matsuo Bashō)', E'Long conversations\nbeside blooming irises – \njoys of life on the road'),
('松尾 芭蕉 (Matsuo Bashō)', E'The lilies!\nThe stems, just as they are,\nthe flowers, just as they are.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The bee emerging\nfrom deep within the peony\ndeparts reluctantly'),
('松尾 芭蕉 (Matsuo Bashō)', E'Slender, so slender\nits stalk bends under dew --\nlittle yellow flower'),
('松尾 芭蕉 (Matsuo Bashō)', E'For those who proclaim\nthey’ve grown weary of children,\nthere are no flowers'),
('松尾 芭蕉 (Matsuo Bashō)', E'Exhausted, I sought\na country inn, but found\nwisteria in bloom'),
('松尾 芭蕉 (Matsuo Bashō)', E'Morning glory trailing --\nAll day the gate-\nbolt''s fastened.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Breakfast enjoyed \nin the fine company of\nmorning glories'),
('松尾 芭蕉 (Matsuo Bashō)', E'The morning glories\nbloom, securing the gate\nin the old fence'),
('松尾 芭蕉 (Matsuo Bashō)', E'bush-clover flowers —\nthey sway but do not drop\ntheir beads of dew'),
('松尾 芭蕉 (Matsuo Bashō)', E'Flower\nunder harvest sun - stranger\nTo bird, butterfly.'),
('松尾 芭蕉 (Matsuo Bashō)', E'without turning\ninto a butterfly, autumn deepens\nfor the worm'),
('松尾 芭蕉 (Matsuo Bashō)', E'Deep into autumn\nand this caterpillar\nstill not a butterfly'),
('松尾 芭蕉 (Matsuo Bashō)', E'A caterpillar\nthis deep in fall\nstill not a butterfly'),
('松尾 芭蕉 (Matsuo Bashō)', E'With every gust of wind,\nthe butterfly changes its place\non the willow.'),
('松尾 芭蕉 (Matsuo Bashō)', E'On the white poppy,\na butterfly’s torn wing\nis a keepsake'),
('松尾 芭蕉 (Matsuo Bashō)', E'butterflies flit…\nthat is all, amid the field\nof sunlight'),
('松尾 芭蕉 (Matsuo Bashō)', E'butterflies flit\nin a field of sunlight\nthat is all'),
('松尾 芭蕉 (Matsuo Bashō)', E'Will you turn toward me?\nI am lonely too,\nThis autumn evening.'),
('松尾 芭蕉 (Matsuo Bashō)', E'As firmly cemented clam-shells\nFall apart in autumn,\nSo I must take to the road again,\nFarewell, my friends.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Farewell, my old fan.\nHaving scribbled on it,\nWhat could I do but tear it\nAt the end of summer?'),
('松尾 芭蕉 (Matsuo Bashō)', E'this autumn\nas-for why grow old\ncloud to bird'),
('松尾 芭蕉 (Matsuo Bashō)', E'this autumn\nwhy am I aging so?\nto the clouds a bird'),
('松尾 芭蕉 (Matsuo Bashō)', E'this autumn\nas reason for growing old\na cloud and a bird'),
('松尾 芭蕉 (Matsuo Bashō)', E'the whole family\nall with white hair and canes\nvisiting graves'),
('松尾 芭蕉 (Matsuo Bashō)', E'souls'' festival\ntoday also there is smoke\nfrom the crematory'),
('松尾 芭蕉 (Matsuo Bashō)', E'lotus pond\nas they are unplucked\nSouls'' Festival'),
('松尾 芭蕉 (Matsuo Bashō)', E'Buddha''s Death Day\nfrom wrinkled praying hands\nthe rosaries'' sound'),
('松尾 芭蕉 (Matsuo Bashō)', E'not to think of yourself\nas someone who did not count --\nFestival of the Souls'),
('松尾 芭蕉 (Matsuo Bashō)', E'all night\nautumn winds being heard\nbehind the mountains'),
('松尾 芭蕉 (Matsuo Bashō)', E'so clear the sound\nechoes to the Big Dipper\nthe fulling block'),
('松尾 芭蕉 (Matsuo Bashō)', E'taken in my hand\nit will vanish in hot tears\nautumn frost'),
('松尾 芭蕉 (Matsuo Bashō)', E'bright red\nthe pitiless sun\nautumn winds'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn wind\nbroken with sadness\nhis mulberry stick'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn winds\nin the sliding door''s opening\na sharp voice'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn wind:\nas thickets in fields are\nFuwa''s barriers'),
('松尾 芭蕉 (Matsuo Bashō)', E'people no longer live\nat the Fuwa Barrier\nin a house with wooden eaves'),
('松尾 芭蕉 (Matsuo Bashō)', E'weathered bones\njust thinking of the wind\nit pierces my body'),
('松尾 芭蕉 (Matsuo Bashō)', E'in the world outside\nis it harvesting time?\nthe grass of my hut'),
('松尾 芭蕉 (Matsuo Bashō)', E'for one touched by monkey cries\nhow is it when a child''s abandoned\nin autumn winds'),
('松尾 芭蕉 (Matsuo Bashō)', E'speaking out\nmy lips are cold\nin autumn wind'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn wind\nin Ise''s shrine cemetery\neven more lonely'),
('松尾 芭蕉 (Matsuo Bashō)', E'walking on and on\neven through I fall down sick\nin fields of clover'),
('松尾 芭蕉 (Matsuo Bashō)', E'from this very day\nerase the inscription with dew\non the bamboo hat'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn colors\nwithout a pot\nof red-brown soup'),
('松尾 芭蕉 (Matsuo Bashō)', E'turn this way!\nI too feel lonely\nlate in autumn'),
('松尾 芭蕉 (Matsuo Bashō)', E'Stone Mountain\nwhiter than the stones\nautumn wind'),
('松尾 芭蕉 (Matsuo Bashō)', E'borrowing sleep\nfrom the scarecrow''s sleeves\nmidnight frost'),
('松尾 芭蕉 (Matsuo Bashō)', E'I would like to use\nthat scarecrow''s tattered clothes\nin this midnight frost'),
('松尾 芭蕉 (Matsuo Bashō)', E'along this road\ngoing with no one\nautumn evening'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn deepens\nthe man next door\nhow is he doing?'),
('松尾 芭蕉 (Matsuo Bashō)', E'saying farewell to people\nfarewell being said to me brings\nautumn in Kiso'),
('松尾 芭蕉 (Matsuo Bashō)', E'I didn''t die!\nthe end of a journey\nis autumn nightfall'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn nears\nmy heart is drawn\nto a four-mat room'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn night\nstriking and making it crumble\nour small talk'),
('松尾 芭蕉 (Matsuo Bashō)', E'blowing stones\nflying from the volcano Asama\nautumn gale'),
('松尾 芭蕉 (Matsuo Bashō)', E'chrysanthemum''s scent\nin the garden a worn-out sandal\njust the sole'),
('松尾 芭蕉 (Matsuo Bashō)', E'rainy day\nthe world''s autumn closes\nBoundary Town'),
('松尾 芭蕉 (Matsuo Bashō)', E'banana plant in autumn storm\nrain drips into tub\nhearing the night'),
('松尾 芭蕉 (Matsuo Bashō)', E'departing autumn\nwith hands spread open\nchestnut burs'),
('松尾 芭蕉 (Matsuo Bashō)', E'Kiso''s chestnuts\nfor a person of the floating world\na souvenir'),
('松尾 芭蕉 (Matsuo Bashō)', E'Over the ruins of a shrine\na chestnut tree\nstill lifts its candles'),
('松尾 芭蕉 (Matsuo Bashō)', E'I’ll take these back\nfor the city slickers –\nsour chestnuts'),
('松尾 芭蕉 (Matsuo Bashō)', E'The Chestnut by the eaves\nIn magnificent bloom\nPasses unnoticed\nBy men of this world.'),
('松尾 芭蕉 (Matsuo Bashō)', E'though autumn winds blow\nit is still green\nbur of the chestnut'),
('松尾 芭蕉 (Matsuo Bashō)', E'The winds of fall\nare blowing, yet how green\nthe chestnut burr.'),
('松尾 芭蕉 (Matsuo Bashō)', E'also green\nit should remain a thing\nthe pepper pod'),
('松尾 芭蕉 (Matsuo Bashō)', E'at Nara\nthe fragrance of chrysanthemums\nancient Buddhas'),
('松尾 芭蕉 (Matsuo Bashō)', E'drinking morning tea\nthe monk is peaceful\nthe chrysanthemum blooms'),
('松尾 芭蕉 (Matsuo Bashō)', E'while growing thin\nwithout a reason\nthe chrysanthemum bud'),
('松尾 芭蕉 (Matsuo Bashō)', E'white chrysanthemum\ncatching in one''s eye\nnary a speck of dust'),
('松尾 芭蕉 (Matsuo Bashō)', E'chrysanthemums\nflowers blooming\nin the stones'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn coolness\nhand and hand paring away\neggplants -- cucumbers'),
('松尾 芭蕉 (Matsuo Bashō)', E'don''t imitate me\nwe are not two halves\nof a muskmelon'),
('松尾 芭蕉 (Matsuo Bashō)', E'ear of the pine tree\nmushroom on a strange tree\nwith a leaf stuck to it'),
('松尾 芭蕉 (Matsuo Bashō)', E'the village so old\nthere''s not a single house\nwithout a persimmon tree'),
('松尾 芭蕉 (Matsuo Bashō)', E'autumn begins\nsea and sprouting rice fields\none green'),
('松尾 芭蕉 (Matsuo Bashō)', E'failing health\nchewing dried seaweed\nmy teeth grate on sand'),
('松尾 芭蕉 (Matsuo Bashō)', E'grabbing at straws\nthe strength to bear\nour parting'),
('松尾 芭蕉 (Matsuo Bashō)', E'on this mountain\ntell me of its sorrow\nwild-yam digger'),
('松尾 芭蕉 (Matsuo Bashō)', E'after the flowers\nall there is left for my haiku\nwisteria beans'),
('松尾 芭蕉 (Matsuo Bashō)', E'The beginning of autumn;\nThe sea and fields,\nAll one same green.'),
('松尾 芭蕉 (Matsuo Bashō)', E'In the bitter radish that\nbites into me, I feel the\nautumn wind'),
('松尾 芭蕉 (Matsuo Bashō)', E'Unknown to birds and butterflies\nA flower blooms\nThe autumn sky'),
('松尾 芭蕉 (Matsuo Bashō)', E'a strange flower\nfor birds and butterflies\nthe autumn sky'),
('松尾 芭蕉 (Matsuo Bashō)', E'Autumn approaches \nand the heart begins to dream \nof four-tatami rooms'),
('松尾 芭蕉 (Matsuo Bashō)', E'Wild boars and all\nare blown along with it --\nstorm-wind of fall!'),
('松尾 芭蕉 (Matsuo Bashō)', E'A autumn wind\nMore white\nThan the rocks in the rocky mountain.'),
('松尾 芭蕉 (Matsuo Bashō)', E'this road go\nperson nonexistent\nwith autumn’s evening'),
('松尾 芭蕉 (Matsuo Bashō)', E'On this road\nwhere nobody else travels\nautumn nightfall'),
('松尾 芭蕉 (Matsuo Bashō)', E'All along this road\nnot a single soul – only\nautumn evening comes'),
('松尾 芭蕉 (Matsuo Bashō)', E'Along this way,\nno travellers.\nDusk in autumn.'),
('松尾 芭蕉 (Matsuo Bashō)', E'My way –\nno-one on the road\nand it’s autumn, getting dark'),
('松尾 芭蕉 (Matsuo Bashō)', E'The first day of the year:\nthoughts come - and there is loneliness;\nthe autumn dusk is here.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Cold as it was\nWe felt secure sleeping together\nIn the same room.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Chilling autumn rains\ncurtain Mount Fuji, then make it\nmore beautiful to see '),
('松尾 芭蕉 (Matsuo Bashō)', E'The winter storm\nHid in the bamboo grove\nAnd quieted away.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Should I hold them in my hand,\nThey will disappear\nIn the warmth of my tears,\nIcy strings of frost.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Hailstones\nGlancing off the rocks\nAt Stony Pass.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Awake at night,\nThe lamp low,\nThe oil freezing.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Winter rain --\nThe field stubble\nHas blackened.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Crossing long fields,\nfrozen in its saddle,\nmy shadow creeps by'),
('松尾 芭蕉 (Matsuo Bashō)', E'Awakened at midnight\nby the sound of the water jar\ncracking from the ice '),
('松尾 芭蕉 (Matsuo Bashō)', E'Water-drawing rites,\nicy sound of monks'' getas\necho long and cold'),
('松尾 芭蕉 (Matsuo Bashō)', E'On the cow shed\nA hard winter rain;\nCock crowing.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The winter leeks\nHave been washed white --\nHow cold it is!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Winter downpour - \neven the monkey \nneeds a raincoat.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Winter solitude--\nin a world of one color\nthe sound of wind.'),
('松尾 芭蕉 (Matsuo Bashō)', E'I''m a wanderer\nso let that be my name –\nthe first winter rain'),
('松尾 芭蕉 (Matsuo Bashō)', E'Winter seclusion –\nsitting propped against\nthe same worn post'),
('松尾 芭蕉 (Matsuo Bashō)', E'On New Year''s Day\neach thought a loneliness\nas winter dusk descends'),
('松尾 芭蕉 (Matsuo Bashō)', E'Along my journey\nthrough this transitory world,\nnew year''s housecleaning'),
('松尾 芭蕉 (Matsuo Bashō)', E'Year’s end, all\ncorners of this\nfloating world, swept.'),
('松尾 芭蕉 (Matsuo Bashō)', E'This first fallen snow\nis barely enough to bend\nthe jonquil leaves'),
('松尾 芭蕉 (Matsuo Bashō)', E'The first snow\nthe leaves of the daffodil\nbending together'),
('松尾 芭蕉 (Matsuo Bashō)', E'The first snow,\nJust enough to bend\nThe leaves of the daffodils.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Tethered horse;\nsnow\nin both stirrups.'),
('松尾 芭蕉 (Matsuo Bashō)', E'First snow\nFalling\nOn the half-finished bridge.'),
('松尾 芭蕉 (Matsuo Bashō)', E'On the polished surface\nOf the divine glass,\nChaste with flowers of snow.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The crescent lights\nThe misty ground.\nBuckwheat flowers.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Come out to view\nthe truth of flowers blooming\nin poverty'),
('松尾 芭蕉 (Matsuo Bashō)', E'New Year’s first snow -- ah --\njust barely enough to tilt\nthe daffodil'),
('松尾 芭蕉 (Matsuo Bashō)', E'Polished and polished\nclean, in the holy mirror\nsnow flowers bloom'),
('松尾 芭蕉 (Matsuo Bashō)', E'Watching for snow,\nthe boozers’ faces –\na flash of lightning'),
('松尾 芭蕉 (Matsuo Bashō)', E'fragrant orchid—\ninto a butterfly’s wings\nit breathes incense'),
('松尾 芭蕉 (Matsuo Bashō)', E'Wake, butterfly -\nIt''s late, we''ve miles\nTo go together.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Butterfly -\nWings curve into\nWhite poppy.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Heard, not seen,\nthe camellia poured rainwater\nwhen it leaned'),
('松尾 芭蕉 (Matsuo Bashō)', E'Misty rain;\nToday is a happy day,\nAlthough Mt. Fuji is unseen.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Even a wild boar\nWith all other things\nBlew in this storm.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The wind from Mt. Fuji\nI put it on the fan.\nHere, the souvenir from Edo.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Tremble, oh my gravemound,\nin time my cries will be\nonly this autumn wind '),
('松尾 芭蕉 (Matsuo Bashō)', E'shaking the grave\nmy weeping voice\nautumn wind'),
('松尾 芭蕉 (Matsuo Bashō)', E'Sleep on horseback,\nThe far moon in a continuing dream,\nSteam of roasting tea.'),
('松尾 芭蕉 (Matsuo Bashō)', E'where''s the moon?\nas the temple bell is --\nsunk in the sea'),
('松尾 芭蕉 (Matsuo Bashō)', E'The moon about to appear,\nall present tonight\nwith their hands on their knees.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Black cloudbank broken\nScatters in the night...Now see\nMoon-lighted mountains!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Husking rice,\na child squints up\nto view the moon.'),
('松尾 芭蕉 (Matsuo Bashō)', E'a peasant’s child\nhusking rice, pauses\nto look at the moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'The clouds come and go,\nproviding a rest for all\nthe moon viewers'),
('松尾 芭蕉 (Matsuo Bashō)', E'Clouds come from time to time --\nand bring to men a chance to rest\nfrom looking at the moon.'),
('松尾 芭蕉 (Matsuo Bashō)', E'All the fields hands\nenjoy a noontime nap after\nthe harvest moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'Whore and monk, we sleep\nunder one roof together,\nmoon in a field of clover'),
('松尾 芭蕉 (Matsuo Bashō)', E'Now I see her face,\nthe old woman, abandoned,\nthe moon her only companion'),
('松尾 芭蕉 (Matsuo Bashō)', E'A cuckoo cries,\nand through a thicket of bamboo \nthe late moon shines'),
('松尾 芭蕉 (Matsuo Bashō)', E'This bright harvest moon\nkeeps me walking all night long\naround the little pond'),
('松尾 芭蕉 (Matsuo Bashō)', E'the moon:\nI wandered around the pond\nall night long'),
('松尾 芭蕉 (Matsuo Bashō)', E'the setting moon\nthe thing that remains\nfour corners of his desk'),
('松尾 芭蕉 (Matsuo Bashō)', E'In the moonlight a worm\nsilently\ndrills through a chestnut'),
('松尾 芭蕉 (Matsuo Bashō)', E'All my friends\nviewing the moon –\nan ugly bunch'),
('松尾 芭蕉 (Matsuo Bashō)', E'Among moon gazers\nat the ancient temple grounds\nnot one beautiful face'),
('松尾 芭蕉 (Matsuo Bashō)', E'viewing the moon\nno one at the party\nhas such a beautiful face'),
('松尾 芭蕉 (Matsuo Bashō)', E'The moon is the guide,\nCome this way to my house,\nSo says the host of a wayside inn.'),
('松尾 芭蕉 (Matsuo Bashō)', E'hair shaved in a moon-shape\nwith their hands on their knees\nin the early hours of night'),
('松尾 芭蕉 (Matsuo Bashō)', E'buying a measure box\nnow I feel differently\nabout moon-viewing'),
('松尾 芭蕉 (Matsuo Bashō)', E'sleeping in the temple\nthe serious-looking face\nis moon-viewing'),
('松尾 芭蕉 (Matsuo Bashō)', E'the full moon\nseven story-songs of a woman\nturning towards the sea'),
('松尾 芭蕉 (Matsuo Bashō)', E'the farmer''s child\nrests from husking rice\nthen sees the moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'famous moon!\ncircling the pond all night\neven to the end'),
('松尾 芭蕉 (Matsuo Bashō)', E'the moon so pure\na wandering monk carries it\nacross the sand'),
('松尾 芭蕉 (Matsuo Bashō)', E'harvest moon\nnorthland weather\nuncertain skies'),
('松尾 芭蕉 (Matsuo Bashō)', E'full autumn moon\nto my gate comes rising\ncrested tide'),
('松尾 芭蕉 (Matsuo Bashō)', E'thin from the Kiso trip\nand still not yet recovered\nthe late harvest moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'blue seas\nbreaking waves smell of rice wine\ntonight''s moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'Autumn full moon,\nthe tides slosh and foam\ncoming in'),
('松尾 芭蕉 (Matsuo Bashō)', E'Mii Temple\knocking on the gate for a wish\ntoday''s moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'your hermitage\nthe moon and chrysanthemums\nplus an acre of rice fields'),
('松尾 芭蕉 (Matsuo Bashō)', E'flower of the harvest moon?\nit only looks that way\na cotton field'),
('松尾 芭蕉 (Matsuo Bashō)', E'butt of the tree\nsee in the cut end\ntoday''s moon'),
('松尾 芭蕉 (Matsuo Bashō)', E'on a bare branch\na crow has settled\nautumn dusk'),
('松尾 芭蕉 (Matsuo Bashō)', E'A solitary\ncrow on a bare branch-\nautumn evening'),
('松尾 芭蕉 (Matsuo Bashō)', E'On dead branches\nCrows remain perched\nAt autumn''s end.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The voices of plovers\nInvite me to stare into the darkness\nOf the Starlit Promontory.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Dark night -\nPlover crying\nFor its nest.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Sparrow, spare\nThe horsefly\nDallying in flowers.'),
('松尾 芭蕉 (Matsuo Bashō)', E'in blossoms\na horsefly plays… don’t eat it\nfriend-sparrow'),
('松尾 芭蕉 (Matsuo Bashō)', E'Sparrows\nIn rape-field,\nBlossom-viewing.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Sparrows in eves\nMice in ceiling -\nCelestial music.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Baby mice in their nest\nsqueak in response\nto the young sparrows'),
('松尾 芭蕉 (Matsuo Bashō)', E'Where cuckoo\nVanishes -\nAn island.'),
('松尾 芭蕉 (Matsuo Bashō)', E'higher than a skylark\nresting in the sky\non a mountain pass'),
('松尾 芭蕉 (Matsuo Bashō)', E'above the moor\nnot attached to anything\na skylark singing'),
('松尾 芭蕉 (Matsuo Bashō)', E'though a skylark sings\nbeating inside\nthe pheasant''s sad cry'),
('松尾 芭蕉 (Matsuo Bashō)', E'All the day long-\nyet not long enough for the skylark,\nsinging, singing.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Do the tea-pickers also,\nhidden in the bushes,\nhear the hototogishu?'),
('松尾 芭蕉 (Matsuo Bashō)', E'Skylark on moor --\nSweet song\nOf non-attachment.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Over skylark''s song\nNoh cry\nOf Pheasant'),
('松尾 芭蕉 (Matsuo Bashō)', E'resting higher\nthan a lark in the sky\na mountain pass'),
('松尾 芭蕉 (Matsuo Bashō)', E'Even these long days\nare not nearly long enough\nfor the skylarks to sing'),
('松尾 芭蕉 (Matsuo Bashō)', E'By a singular stroke\nOf luck, I saw a solitary hawk circling\nAbove the promontory of Irago.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Unknowingly he guided us\nover pathless hills\nwith wisps of hay'),
('松尾 芭蕉 (Matsuo Bashō)', E'My eyes following\nuntil the bird was lost at sea\nfound a small island'),
('松尾 芭蕉 (Matsuo Bashō)', E'A mountain pheasant cry\nfills me with fond longing for\nfather and mother'),
('松尾 芭蕉 (Matsuo Bashō)', E'The lightning flashes\nAnd slashing through the darkness,\nA night-heron’s screech.'),
('松尾 芭蕉 (Matsuo Bashō)', E'O bush warblers!\nNow you’ve shit all over\nmy rice cake on the porch'),
('松尾 芭蕉 (Matsuo Bashō)', E'the sea darkens —\nthe voices of the wild ducks\nare faintly white'),
('松尾 芭蕉 (Matsuo Bashō)', E'Seas slowly darken\nand the wild duck''s plaintive cry\ngrows faintly white'),
('松尾 芭蕉 (Matsuo Bashō)', E'very exciting\nyet after awhile so sad\ncormorant fishing'),
('松尾 芭蕉 (Matsuo Bashō)', E'a sick wild duck\nfalling down with the dark cold\nto sleep overnight'),
('松尾 芭蕉 (Matsuo Bashō)', E'cloud-parting friend!\ntemporarily this wild goose\nmust go away'),
('松尾 芭蕉 (Matsuo Bashō)', E'With a warbler for\na soul, it sleeps peacefully,\nthis mountain willow'),
('松尾 芭蕉 (Matsuo Bashō)', E'The warbler sings\namong new shoots of bamboo\nof coming old age'),
('松尾 芭蕉 (Matsuo Bashō)', E'Delight, then sorrow,\naboard the cormorant\nfishing boat'),
('松尾 芭蕉 (Matsuo Bashō)', E'But for a woodpecker\ntapping at a post, no sound\nat all in the house'),
('松尾 芭蕉 (Matsuo Bashō)', E'Even in Kyoto,\nhow I long for Kyoto\nwhen the cuckoo sings'),
('松尾 芭蕉 (Matsuo Bashō)', E'Lead my pony\nacross this wide moor to where\nthe cuckoo sings'),
('松尾 芭蕉 (Matsuo Bashō)', E'The shallows –\na crane’s thighs splashed\nin cool waves'),
('松尾 芭蕉 (Matsuo Bashō)', E'A dragonfly, trying to –\noops, hang on to the upside\nof a blade of grass'),
('松尾 芭蕉 (Matsuo Bashō)', E'temple bell\nalso sounds like it is\ncicada''s voice'),
('松尾 芭蕉 (Matsuo Bashō)', E'cricket\nforgetting sounds with its cry\nby the fireplace'),
('松尾 芭蕉 (Matsuo Bashō)', E'in the cow shed\nmosquito''s voice darkens\nlingering heat'),
('松尾 芭蕉 (Matsuo Bashō)', E'bagworm''s place\nit seems to be inside\nthe cherry blossoms'),
('松尾 芭蕉 (Matsuo Bashō)', E'bagworms\nto hear their songs\ncome to my hut'),
('松尾 芭蕉 (Matsuo Bashō)', E'spiders have a cry?\nwell, what is chirping\nautumn''s wind?'),
('松尾 芭蕉 (Matsuo Bashō)', E'secretly at night\na worm under the moon\nbores into a chestnut'),
('松尾 芭蕉 (Matsuo Bashō)', E'With what kind of voice\nwould the spider cry\nin the autumn wind?'),
('松尾 芭蕉 (Matsuo Bashō)', E'Firefly viewing -\nDrunken steersman,\nDrunken boat.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The dragonfly\nCan''t quite land\nOn that blade of grass.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Dying cricket,\nhow he sings out\nhis life!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Gray hairs being plucked,\nand from below my pillow\na cricket singing'),
('松尾 芭蕉 (Matsuo Bashō)', E'Ungraciously, under\na great soldier''s empty helmet,\na cricket sings'),
('松尾 芭蕉 (Matsuo Bashō)', E'how piteous!\nbeneath the soldiers helmet\nchirps a cricket'),
('松尾 芭蕉 (Matsuo Bashō)', E'a terrible sound –\nthe gilded helmet’s\ntrapped cricket'),
('松尾 芭蕉 (Matsuo Bashō)', E'Cicadas singing --\nNo sign\nOf dying soon.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Calm and serene\nThe sound of a cicada\nPenetrates the rock'),
('松尾 芭蕉 (Matsuo Bashō)', E'stillness\npiercing the rocks\ncicada''s shrill'),
('松尾 芭蕉 (Matsuo Bashō)', E'Lonely silence,\na single cicada''s cry\nsinking into stone'),
('松尾 芭蕉 (Matsuo Bashō)', E'How still it is!\nSinking into the stones,\nthe locusts'' trill.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Eaten alive by\nlice and fleas -- now the horse\nbeside my pillow pees'),
('松尾 芭蕉 (Matsuo Bashō)', E'at my poor hovel\nthere’s one thing I can offer —\nsmall mosquitoes'),
('松尾 芭蕉 (Matsuo Bashō)', E'The usually hateful crow:\nhe, too -- this morning,\non the snow!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Even that old horse\nis something to see this\nsnow-covered morning'),
('松尾 芭蕉 (Matsuo Bashō)', E'What luck!\nThe southern valley\nMake snow fragrant.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Hello! Light the fire!\nI''ll bring inside\na lovely bright ball of snow'),
('松尾 芭蕉 (Matsuo Bashō)', E'to Kyoto\nstill half the sky to go—\nsnowy clouds'),
('松尾 芭蕉 (Matsuo Bashō)', E'Only half the way I came\nTo the ancient capital,\nAnd above my head\nClouds heavy with snow.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Crossing half the sky,\non my way to the capital,\nbig clouds promise snow'),
('松尾 芭蕉 (Matsuo Bashō)', E'Not even a hat --\nand cold rain falling on me?\nTut-tut! Think of that!'),
('松尾 芭蕉 (Matsuo Bashō)', E'A cold rain starting\nAnd no hat --\nSo?'),
('松尾 芭蕉 (Matsuo Bashō)', E'under my tree-roof\nslanting lines of April rain\nseparate to drops'),
('松尾 芭蕉 (Matsuo Bashō)', E'The banana tree\nblown by winds pours raindrops\ninto the bucket'),
('松尾 芭蕉 (Matsuo Bashō)', E'How admirable,\nHe who thinks not, "Life is fleeting,"\nWhen he sees the lightning!'),
('松尾 芭蕉 (Matsuo Bashō)', E'How very noble!\nOne who finds no satori\nin the lightning-flash'),
('松尾 芭蕉 (Matsuo Bashō)', E'Shake, oh grave!\nThe autumn wind\nIs the voice of my wailing.'),
('松尾 芭蕉 (Matsuo Bashō)', E'I''ll on a journey,\nall about the dreary fields\nfly my broken dreams.'),
('松尾 芭蕉 (Matsuo Bashō)', E'DEATH POEM\nSick on my journey,\nonly my dreams will wander\nthese desolate moors\nA weathered skeleton \nin windy fields of memory,\npiercing like a knife'),
('松尾 芭蕉 (Matsuo Bashō)', E'From among the peach-trees\n"Blooming everywhere,"\nThe first cherry blossoms.');
