DROP TABLE IF EXISTS haiku;

CREATE TABLE haiku (
  id SERIAL PRIMARY KEY NOT NULL,
  author VARCHAR(255) NOT NULL,
  content TEXT NOT NULL
  
);

INSERT INTO haiku (author, content) 
VALUES ('松尾 芭蕉 (Matsuo Bashō)', E'First Line\nSecond Line\nThird Line'),
('松尾 芭蕉 (Matsuo Bashō)', E'Scarecrow in the hillock\nPaddy field --\nHow unaware!  How useful!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Passing through the world\nIndeed this is just\nSogi''s rain shelter.'),
('松尾 芭蕉 (Matsuo Bashō)', E'A wild sea-\nIn the distance over Sado\nThe Milky Way.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The she cat -\nGrown thin\nFrom love and barley.'),
('松尾 芭蕉 (Matsuo Bashō)', E'How wild the sea is,\nand over Sado Island,\nthe River of Heaven'),
('松尾 芭蕉 (Matsuo Bashō)', E'Morning and evening\nSomeone waits at Matsushima!\nOne-sided love.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Wrapping dumplings in \nbamboo leaves, with one finger\nshe tidies her hair'),
('松尾 芭蕉 (Matsuo Bashō)', E'On Buddha''s birthday\na spotted fawn is born –\njust like that'),
('松尾 芭蕉 (Matsuo Bashō)', E'On Buddha''s deathday,\nwrinkled tough old hands pray –\nthe prayer beads'' sound'),
('松尾 芭蕉 (Matsuo Bashō)', E'I like to wash,\nthe dust of this world\nIn the droplets of dew.'),
('松尾 芭蕉 (Matsuo Bashō)', E'With dewdrops dripping,\nI wish somehow I could wash \nthis perishing world'),
('松尾 芭蕉 (Matsuo Bashō)', E'Won''t you come and see\nloneliness? Just one leaf\nfrom the kiri tree.'),
('松尾 芭蕉 (Matsuo Bashō)', E'moonless night...\na powerful wind embraces\nthe ancient cedars'),
('松尾 芭蕉 (Matsuo Bashō)', E'Behind Ise Shrine,\nunseen, hidden by the fence,\nBuddha enters nirvana'),
('松尾 芭蕉 (Matsuo Bashō)', E'This ruined temple\nshould have its sad tale told only\nby a clam digger '),
('松尾 芭蕉 (Matsuo Bashō)', E'in my new clothing\ni feel so different, i must\nlook like someone else'),
('松尾 芭蕉 (Matsuo Bashō)', E'low tide morning...\nthe willow skirts are tailed\nin stinking mud'),
('松尾 芭蕉 (Matsuo Bashō)', E'A green willow,\ndripping down into the mud,\nat low tide.'),
('松尾 芭蕉 (Matsuo Bashō)', E'a clear waterfall —\ninto the ripples\nfall green pine-needles'),
('松尾 芭蕉 (Matsuo Bashō)', E'overhanging pine...\nadding its mite of needles\nto the waterfall'),
('松尾 芭蕉 (Matsuo Bashō)', E'The pine tree of Shiogoshi\nTrickles all night long\nShiny drops of moonlight.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Culture''s beginnings:\nrice-planting songs from the heart\nof the country'),
('松尾 芭蕉 (Matsuo Bashō)', E'Singing, planting rice,\nvillage songs more lovely\nthan famous city poems'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring air --\nWoven moon\nAnd plum scent.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Heated spring air\nIn tiny waves of an inch or two -\nAbove wintery grass.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Fresh spring!\nThe world is only Nine days old -\nThese fields and mountains!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring!\nA nameless hill\nin the haze.'),
('松尾 芭蕉 (Matsuo Bashō)', E'it is spring!\na hill without a name\nin thin haze'),
('松尾 芭蕉 (Matsuo Bashō)', E'Oh, these spring days!\nA nameless little mountain,\nwrapped in morning haze!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring too, very soon!\nThey are setting the scene for it --\nplum tree and moon.'),
('松尾 芭蕉 (Matsuo Bashō)', E'From all directions\nWinds bring petals of cherry\nInto the grebe lake.'),
('松尾 芭蕉 (Matsuo Bashō)', E'The leafless cherry,\nOld as a toothless woman,\nBlooms in flowers,\nMindful of its youth.'),
('松尾 芭蕉 (Matsuo Bashō)', E'That great blue oak\nindifferent to all blossoms\nappears more noble'),
('松尾 芭蕉 (Matsuo Bashō)', E'The oak tree stands\nnoble on the hill even in\ncherry blossom time'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring rain\nconveyed under the trees\nin drops.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring rain\nLeaking through the roof,\nDripping from the wasps'' nest.'),
('松尾 芭蕉 (Matsuo Bashō)', E'In this warm spring rain,\ntiny leaves are sprouting\nfrom the eggplant seed'),
('松尾 芭蕉 (Matsuo Bashō)', E'The sun''s way:\nhollyhocks turn toward it\nthrough all the rains of May.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Spring departs.\nBirds cry\nFishes'' eyes are filled with tears'),
('松尾 芭蕉 (Matsuo Bashō)', E'No blossoms and no moon,\nand he is drinking sake\nall alone!'),
('松尾 芭蕉 (Matsuo Bashō)', E'Temple bells die out.\nThe fragrant blossoms remain.\nA perfect evening!'),
('松尾 芭蕉 (Matsuo Bashō)', E'A little girl under a peach tree,\nWhose blossoms fall into the entrails\nOf the earth.'),
('松尾 芭蕉 (Matsuo Bashō)', E'By the old temple,\npeach blossoms;\na man treading rice.'),
('松尾 芭蕉 (Matsuo Bashō)', E'Unknown spring --\nPlum blossom\nBehind the mirror.'),
('松尾 芭蕉 (Matsuo Bashō)', E'With plum blossom scent,\nthis sudden sun emerges\nalong a mountain trail'),
('松尾 芭蕉 (Matsuo Bashō)', E'Very brief:\nGleam of blossoms in the treetops\nOn a moonlit night.'),
('松尾 芭蕉 (Matsuo Bashō)', E'From among the peach-trees\n"Blooming everywhere,"\nThe first cherry blossoms.');
